# 
#  (C) by Remo Dentato (rdentato@gmail.com)
# 
# This software is distributed under the terms of the BSD license:
#   http://creativecommons.org/licenses/BSD/
#   http://opensource.org/licenses/bsd-license.php
#
 
TOP=../../

include $(TOP)config.mk

include sts_tests.mk
  
clean:
	$(RM) $(STS_TESTS) 
	$(RM) $(STS_OBJS) 
	$(RM) gmon.out

include $(TOP)targets.mk
